name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up micromamba (arm64)
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: test
          create-args: >-
            python=3.11
            micro_sam
          channels: conda-forge
          cache-environment: true
          init-shell: bash

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          micromamba run -n test python -m pip install --upgrade pip
          micromamba run -n test pip install pytest pytest-mock
          micromamba run -n test pip install -r requirements.txt
          micromamba run -n test pip install .

      - name: Run tests
        shell: bash -l {0}
        run: |
          micromamba run -n test pytest tests/
